spring:
  application:
    name: spring-could-consumer

server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost/eureka/

ribbon:
  #请求处理的超时时间
  ReadTimeout: 1000
  #请求连接的超时时间
  ConnectTimeout: 1000
